name: Build Wheels

on: [workflow_dispatch, push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - os: ubuntu-20.04
          - os: windows-2019
         # - os: macos-10.15

    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/bootstrap_platform

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.1
        env: 
          CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/.conan/conan_paths.cmake
          
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl