# - Build Python Wheels
# - Deploy to TestPyPI
# - Download from TestPyPI
# - Run tests on downloaded artifacts
# - Deploy to real PyPI
name: Deploy_PyPI

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call_build_wheels:
    name: Call 🗣️🔨 Build Wheels
    uses: ./.github/workflows/build-wheels.yml

  publish_testpypi:
    name: Publish distribution 📦 to TestPyPI
    needs: call_build_wheels
    runs-on: ubuntu-20.04
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v3
        with:
          name: "openassetio-wheels"
          path: dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_ACCESS_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  publish_pypi:
    name: Publish distribution 📦 to PyPI
    needs: verify_test_pypi
    runs-on: ubuntu-20.04
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v3
        with:
          name: "openassetio-wheels"
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_ACCESS_TOKEN }}
