name: Deploy_PyPI

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:

  publish_pypi:
    name: Publish distribution 📦 to PyPI
    runs-on: ubuntu-20.04
    steps:
      # This action will download the artifact for workflow runs that
      # happen for this actual commit (the commit that the tag points to).
      # It also restores the files timestamps.
      # This does however mean that when making a release, you must be
      # sure that the build-wheels job on main has completed
      - name: Download wheels from commit ${{ github.sha }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: openassetio-wheels
          path: dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_ACCESS_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_ACCESS_TOKEN }}
