name: Upload Release Builds

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload-release-builds:
    name: Upload release builds
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - name: Download wheels from commit ${{ github.sha }}
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          path: dist

      - run: ls -R dist

#      - name: Upload release builds
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run:
#          gh release upload ${GITHUB_REF#refs/tags/} ${{ github.workspace }}/dist/openassetio-${{ matrix.config.os }}.zip