name: Upload Release Builds

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload-release-builds:
    name: Upload release builds
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts from commit ${{ github.sha }}
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          path: dist

      - name: Print dist directory
        run: ls -R dist

      - name: Upload release builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ${{ github.workspace }}/dist/openassetio*; do
            gh release upload ${{ github.event.release.tag_name }} "$file"
          done
